# Generated by Django 4.0.6 on 2022-08-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0008_remove_producto_disponibilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
