# Generated by Django 4.1 on 2022-08-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0008_cliente_empleado_delete_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='claveEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=30)),
            ],
        ),
    ]
