# Generated by Django 4.1 on 2022-08-26 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0009_claveempleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='claveEmpleado',
        ),
    ]
