# Generated by Django 4.0.6 on 2022-08-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0009_remove_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='img', verbose_name='imagen'),
        ),
    ]
