# Generated by Django 4.1 on 2022-08-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0010_delete_claveempleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
