# Generated by Django 4.0.6 on 2022-09-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0013_rename_producto_bicicletas_alter_bicicletas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicletas',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
