# Generated by Django 4.1 on 2022-08-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0014_rename_chatmensaje_canalmensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canalmensaje',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='canalmensaje',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='canalusuario',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='canalusuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Canal',
        ),
        migrations.DeleteModel(
            name='CanalMensaje',
        ),
        migrations.DeleteModel(
            name='CanalUsuario',
        ),
    ]
