# Generated by Django 4.0.6 on 2022-09-06 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0015_enviarmensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnviarMensajes',
        ),
    ]
