# Generated by Django 4.0.6 on 2022-09-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0016_delete_enviarmensajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
