# Generated by Django 4.0.6 on 2022-09-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0017_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicletas',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
