# Generated by Django 4.0.6 on 2022-09-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0018_alter_bicicletas_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
