# Generated by Django 4.0.6 on 2022-09-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0019_delete_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='emial',
            new_name='email',
        ),
    ]
