# Generated by Django 4.1.1 on 2022-09-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0023_alter_avatar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='nosotrosblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
