# Generated by Django 4.1.1 on 2022-09-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0024_nosotrosblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nosotrosblog',
        ),
    ]
